language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - cd udemy_django_rest_tutorial

before_script: 
  - pip install docker-compose

script:
  - docker-compose run udemy_django_rest_tutorial sh -c "python manage.py test && flake8"