version: "3"

services:
  udemy_django_rest_tutorial:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./udemy_django_rest_tutorial:/udemy_django_rest_tutorial
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=udemy_django_rest_tutorial
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=udemy_django_rest_tutorial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
